version: '1.4'

services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d:ro
            - ./app:/var/www
            - ./docker/nginx/log:/var/log/nginx
        links:
            - php
    php:
        build: ./docker/php
        links:
            - mysql
        volumes:
            - ./app:/var/www:cached
            - ./docker/php/conf.d:/usr/local/etc/php/custom.d

    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: krasmadelhpi
            MYSQL_DATABASE: ELECTRO
            MYSQL_USER: root
            MYSQL_PASSWORD: krasmadelhpi
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10